spring:
  profiles: prod
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}

  jpa:
    database: POSTGRESQL
    database_platform: org.hibernate.dialect.PostgreSQLDialect
    generateDdl: true
    properties:
      hibernate:
       jdbc:
        lob:
          non_contextual_creation: true
        connection:
          characterEnconding: UTF-8
          charSet: UTF-8



logging:
  level:
    org.springframework: INFO

server:
  port: ${PORT:5000}

---

spring:
  profiles: dev
  datasource:
      driverClassName: org.h2.Driver
  jpa:
    database: h2
    database_platform: org.hibernate.dialect.H2Dialect
    generateDdl: true
    properties:
      hibernate:
       jdbc:
        lob:
          non_contextual_creation: true
        connection:
          characterEnconding: UTF-8
          charSet: UTF-8

logging:
   level:
       root: INFO
       org.hibernate.SQL: DEBUG



server:
  port: ${PORT:5000}